name: gis_stack

services:

  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - gis_postgis_data:/var/lib/postgresql/data

    ports:
      - "${POSTGRES_PORT}:5432"

    networks:
      - backend_net

    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 1G

  gis-engine:
    image: gis-engine:latest
    build:
      context: ./gis-engine

    container_name: gis-engine
    restart: unless-stopped

    # Mismo .env para acceder a PostGIS
    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgis
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - /home/chris/docker_data:/home/chris/docker_data

    networks:
      - backend_net

    deploy:
      resources:
        limits:
          memory: 6G
          cpus: "4.0"
        reservations:
          memory: 2G

volumes:
  gis_postgis_data:

networks:
  backend_net:
    name: docker_data_backend_net
    driver: bridge