services:

  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgis:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend_net

  gis-engine:
    build:
      context: ./gis-engine
      dockerfile: Dockerfile
    image: gis-engine:latest
    container_name: gis-engine
    restart: unless-stopped
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge